CREATE DATABASE Libreria;
USE Libreria;

CREATE TABLE AUTOR (
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NombreAutor VARCHAR (50) NOT NULL
);

CREATE TABLE LIBRO (
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IdAutor INT NOT NULL,
Titulo VARCHAR (100) NOT NULL,
Capitulos INT NOT NULL,
Paginas INT NOT NULL,
Precio FLOAT NOT NULL 
FOREIGN KEY (IdAutor) REFERENCES AUTOR (Id)
);
